/*
Parses the raw BIOS E820 memory map generated by the bootloader. It calculates how much RAM is safely usable by the OS
*/


#include "e280.h"
#include "../console/console.h"

void e820_print_map(){
    unsigned short count = *(unsigned short*)MEMORY_COUNT_ADDR;
    printk("\nE820 Entries: ");
    printk_dec(count);
    printk("\n");

    e820_entry_t* map = (e820_entry_t*) MEMORY_MAP_ADDR;

    for(int i=0; i<count; i++){
        printk("\nEntry: ");
        printk_dec(i+1);
        printk("\n");

        printk("Base : ");
        printk_hex((unsigned int)map[i].base);
        printk("\n");

        printk("Length : ");
        printk_hex((unsigned int)map[i].length);
        printk("\n");

        printk("Type : ");
        printk_hex(map[i].type);
        printk("\n");
    }
    
}

unsigned int e820_total_usable_ram(){
    unsigned short count = *(unsigned short*)MEMORY_COUNT_ADDR;
    e820_entry_t* map = (e820_entry_t*) MEMORY_MAP_ADDR;

    unsigned int total = 0;
    for(int i=0; i<count; i++){
        if(map[i].type == 1){
            total += (unsigned int)map[i].length;
        }
    }

    return total;
}

unsigned int e820_total_reserved_ram(){
    unsigned short count = *(unsigned short*)MEMORY_COUNT_ADDR;
    e820_entry_t* map = (e820_entry_t*) MEMORY_MAP_ADDR;

    unsigned int total = 0;
    for(int i=0; i<count; i++){
        if(map[i].type != 1){
            total += (unsigned int)map[i].length;
        }
    }

    return total;
}

unsigned int e820_largest_usable_region(){
    unsigned short count = *(unsigned short*)MEMORY_COUNT_ADDR;
    e820_entry_t* map = (e820_entry_t*) MEMORY_MAP_ADDR;

    unsigned int largest = 0;
    for(int i=0; i<count; i++){
        if(map[i].type != 1) continue;

        if((unsigned int)map[i].length > largest){
            largest = (unsigned int)map[i].length;
        }
    }

    return largest;
}