/*
Calculates and prints the physical memory footprint of the kernel. It uses symbols generated by the linker script to find the safe starting address for the Physical Memory Allocator.
*/

#include "memory_info.h"
#include "../console/console.h"

extern char kernel_start;
extern char kernel_end;

// Calculates the kernel size and finds the next safe 4KB aligned memory address to start the heap.
void memory_info_print(){

    unsigned int start = (unsigned int)&kernel_start;
    unsigned int end   = (unsigned int)&kernel_end;

    printk("\nKernel Start : ");
    printk_hex(start);

    printk("\nKernel End   : ");
    printk_hex(end);

    printk("\nKernel Size  : ");

    unsigned int size = end - start;
    printk_hex(size);
    printk(" bytes\n");

    unsigned int heap_start = (end + 0xFFF) & 0xFFFFF000;
    printk("\nSuggested Heap Start : ");
    printk_hex(heap_start);
    printk("\n");
}
