/*
Calculates and prints the physical memory footprint of the kernel. It uses symbols generated by the linker script to find the safe starting address for the Physical Memory Allocator.
*/

#include "memory_info.h"
#include "pmm.h"
#include "../console/console.h"
#include "heap.h"

extern char kernel_start;
extern char kernel_end;

// Calculates the kernel size and finds the next safe 4KB aligned memory address to start the heap.
void memory_info_print(){

    unsigned int start = (unsigned int)&kernel_start;
    unsigned int end = (unsigned int)&kernel_end;

    printk("\nKernel Start : ");
    printk_hex(start);
    printk("\nKernel End   : ");
    printk_hex(end);
    printk("\nKernel Size  : ");
    printk_hex(end - start);
    printk(" bytes\n");

    printk("\nPMM Start : ");
    printk_hex(pmm_bitmap_start());
    printk("\nPMM End : ");
    printk_hex(pmm_bitmap_end());
    printk("\nPMM Size : ");
    printk_hex(pmm_bitmap_end() - pmm_bitmap_start());
    printk(" bytes\n");

    unsigned int heap_start = get_heap_start();
    printk("\nHeap Start : ");
    printk_hex(heap_start);
    printk("\n");
}
